export * from "./user.controller"
export * from "./salleentrainement.controller"
export * from "./exercices.controller"
export * from "./salledesport.controller"
export * from "./defis.controller"
export * from "./seance.controller"
export * from "./recompenses.controller"